
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA CREAR DATABASE IDENTIFICADOR INT LPAREN NUMERO PUNTOYCOMA RPAREN TABLE USAR VARCHARcomando : CREAR DATABASE IDENTIFICADOR PUNTOYCOMAcomando : USAR DATABASE IDENTIFICADOR PUNTOYCOMAcomando : CREAR TABLE IDENTIFICADOR LPAREN columnas RPAREN PUNTOYCOMAcolumnas : columnas COMA columnacolumnas : columnacolumna : IDENTIFICADOR tipotipo : INT\n            | VARCHAR LPAREN NUMERO RPAREN'
    
_lr_action_items = {'CREAR':([0,],[2,]),'USAR':([0,],[3,]),'$end':([1,10,12,22,],[0,-1,-2,-3,]),'DATABASE':([2,3,],[4,6,]),'TABLE':([2,],[5,]),'IDENTIFICADOR':([4,5,6,11,20,],[7,8,9,13,13,]),'PUNTOYCOMA':([7,9,19,],[10,12,22,]),'LPAREN':([8,18,],[11,21,]),'INT':([13,],[17,]),'VARCHAR':([13,],[18,]),'RPAREN':([14,15,16,17,23,24,25,],[19,-5,-6,-7,-4,25,-8,]),'COMA':([14,15,16,17,23,25,],[20,-5,-6,-7,-4,-8,]),'NUMERO':([21,],[24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),'columnas':([11,],[14,]),'columna':([11,20,],[15,23,]),'tipo':([13,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> CREAR DATABASE IDENTIFICADOR PUNTOYCOMA','comando',4,'p_comando_crear_db','parser.py',5),
  ('comando -> USAR DATABASE IDENTIFICADOR PUNTOYCOMA','comando',4,'p_comando_usar_db','parser.py',9),
  ('comando -> CREAR TABLE IDENTIFICADOR LPAREN columnas RPAREN PUNTOYCOMA','comando',7,'p_comando_crear_tabla','parser.py',13),
  ('columnas -> columnas COMA columna','columnas',3,'p_columnas','parser.py',17),
  ('columnas -> columna','columnas',1,'p_columnas_una','parser.py',21),
  ('columna -> IDENTIFICADOR tipo','columna',2,'p_columna','parser.py',25),
  ('tipo -> INT','tipo',1,'p_tipo','parser.py',29),
  ('tipo -> VARCHAR LPAREN NUMERO RPAREN','tipo',4,'p_tipo','parser.py',30),
]
